import React,{useCallback,useState} from 'react';
import {SafeAreaView,ScrollView,Text,TextInput,TouchableOpacity,View,StyleSheet} from 'react-native';
import {brokerAccountsApi} from '../services/brokerAccountsApi';
import {API_BASE_URL} from '../services/marketDataApi';
import {withAuthHeaders} from '../services/authSession';

async function health(id){const r=await fetch(`${API_BASE_URL}/broker-accounts/${id}/health`,{headers:withAuthHeaders()});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||`Health check failed (${r.status})`);return b;}

export default function BrokerAccountsScreen(){
 const[accounts,setAccounts]=useState([]),[broker,setBroker]=useState(''),[label,setLabel]=useState(''),[credentials,setCredentials]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[checking,setChecking]=useState(null),[healthById,setHealthById]=useState({});
 const load=useCallback(async()=>{try{setError('');setAccounts(await brokerAccountsApi.list())}catch(e){setError(e.message||'Unable to load broker accounts')}},[]);
 React.useEffect(()=>{load()},[load]);
 async function add(){try{setLoading(true);setError('');await brokerAccountsApi.create(broker,label,credentials);setBroker('');setLabel('');setCredentials('');await load()}catch(e){setError(e.message||'Unable to add broker account')}finally{setLoading(false)}}
 async function remove(id){try{await brokerAccountsApi.remove(id);setHealthById(x=>{const n={...x};delete n[id];return n});await load()}catch(e){setError(e.message||'Unable to remove broker account')}}
 async function check(id){try{setChecking(id);setError('');setHealthById(x=>({...x,[id]:await health(id)}))}catch(e){setError(e.message||'Unable to check connection')}finally{setChecking(null)}}
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Broker Accounts</Text><Text style={s.note}>Credentials are encrypted by the server and are never returned to this screen.</Text><View style={s.card}><TextInput value={broker} onChangeText={setBroker} placeholder="Broker" style={s.input}/><TextInput value={label} onChangeText={setLabel} placeholder="Account label" style={s.input}/><TextInput value={credentials} onChangeText={setCredentials} placeholder="Broker API credentials" secureTextEntry style={s.input}/><TouchableOpacity disabled={loading} onPress={add} style={s.button}><Text style={s.bt}>{loading?'Saving...':'Add Account'}</Text></TouchableOpacity></View>{error?<Text style={s.error}>{error}</Text>:null}{accounts.map(a=>{const h=healthById[a.id];return <View key={a.id} style={s.account}><View style={{flex:1}}><Text style={s.broker}>{a.broker}</Text><Text>{a.account_label}</Text><Text>Status: {a.status}</Text>{h?<Text style={s.health}>Connection: {h.status|| (h.configured?'configured':'not configured')} {h.live_trading_enabled?'':'• live trading disabled'}</Text>:null}</View><View><TouchableOpacity onPress={()=>check(a.id)} disabled={checking===a.id}><Text style={s.action}>{checking===a.id?'Checking...':'Check'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>remove(a.id)}><Text style={s.remove}>Remove</Text></TouchableOpacity></View></View>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1},content:{padding:20},title:{fontSize:26,fontWeight:'800',marginBottom:8},note:{fontSize:12,color:'#666',marginBottom:16},card:{borderWidth:1,borderColor:'#ddd',borderRadius:14,padding:16,marginBottom:14},input:{borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:12,marginBottom:10},button:{backgroundColor:'#111',padding:14,borderRadius:10},bt:{color:'#fff',textAlign:'center',fontWeight:'700'},error:{color:'#b00020',marginBottom:12},account:{borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:14,marginBottom:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},broker:{fontWeight:'800',fontSize:16},health:{marginTop:4,fontSize:12},action:{fontWeight:'700',paddingBottom:10},remove:{fontWeight:'700'}});
