import React,{useCallback,useState} from 'react';
import {SafeAreaView,ScrollView,Text,TextInput,TouchableOpacity,View,StyleSheet} from 'react-native';
import {brokerAccountsApi} from '../services/brokerAccountsApi';
import {startUpstoxOAuth} from '../services/upstoxOAuth';
import {getBrokerProfile,getBrokerPositions,getBrokerHoldings} from '../services/brokerAccountState';

export default function BrokerAccountsScreen(){
 const[accounts,setAccounts]=useState([]),[broker,setBroker]=useState(''),[label,setLabel]=useState(''),[credentials,setCredentials]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[oauthLoading,setOauthLoading]=useState(false),[stateById,setStateById]=useState({}),[loadingState,setLoadingState]=useState(null);
 const load=useCallback(async()=>{try{setError('');setAccounts(await brokerAccountsApi.list())}catch(e){setError(e.message||'Unable to load broker accounts')}},[]); React.useEffect(()=>{load()},[load]);
 async function add(){try{setLoading(true);setError('');await brokerAccountsApi.create(broker,label,credentials);setBroker('');setLabel('');setCredentials('');await load()}catch(e){setError(e.message||'Unable to add broker account')}finally{setLoading(false)}}
 async function connectUpstox(){try{setOauthLoading(true);setError('');await startUpstoxOAuth(label||'Upstox')}catch(e){setError(e.message||'Unable to start Upstox connection')}finally{setOauthLoading(false)}}
 async function remove(id){try{await brokerAccountsApi.remove(id);setStateById(x=>{const n={...x};delete n[id];return n});await load()}catch(e){setError(e.message||'Unable to remove broker account')}}
 async function refreshState(id){try{setLoadingState(id);setError('');const [profile,positions,holdings]=await Promise.all([getBrokerProfile(id),getBrokerPositions(id),getBrokerHoldings(id)]);setStateById(x=>({...x,[id]:{profile,positions,holdings}}))}catch(e){setError(e.message||'Unable to load broker state')}finally{setLoadingState(null)}}
 const count=v=>Array.isArray(v)?v.length:Array.isArray(v?.data)?v.data.length:null;
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Broker Accounts</Text><Text style={s.note}>OAuth is preferred for Upstox. Tokens remain encrypted server-side.</Text><View style={s.card}><TextInput value={label} onChangeText={setLabel} placeholder="Upstox account label" style={s.input}/><TouchableOpacity disabled={oauthLoading} onPress={connectUpstox} style={s.oauth}><Text style={s.oauthText}>{oauthLoading?'Opening Upstox...':'Connect Upstox'}</Text></TouchableOpacity></View><Text style={s.sub}>Manual broker credentials</Text><View style={s.card}><TextInput value={broker} onChangeText={setBroker} placeholder="Broker" style={s.input}/><TextInput value={label} onChangeText={setLabel} placeholder="Account label" style={s.input}/><TextInput value={credentials} onChangeText={setCredentials} placeholder="Broker API credentials" secureTextEntry style={s.input}/><TouchableOpacity disabled={loading} onPress={add} style={s.button}><Text style={s.bt}>{loading?'Saving...':'Add Account'}</Text></TouchableOpacity></View>{error?<Text style={s.error}>{error}</Text>:null}{accounts.map(a=>{const d=stateById[a.id];return <View key={a.id} style={s.account}><View style={{flex:1}}><Text style={s.broker}>{a.broker}</Text><Text>{a.account_label}</Text><Text>Status: {a.status}</Text>{d?<View style={s.state}><Text style={s.section}>Profile</Text><Text>{d.profile?.data?.user_name||d.profile?.user_name||d.profile?.data?.email||'Connected'}</Text><Text style={s.section}>Positions</Text><Text>{count(d.positions)??'—'} records</Text><Text style={s.section}>Holdings</Text><Text>{count(d.holdings)??'—'} records</Text></View>:null}</View><View><TouchableOpacity onPress={()=>refreshState(a.id)} disabled={loadingState===a.id}><Text style={s.action}>{loadingState===a.id?'Loading...':'Refresh State'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>remove(a.id)}><Text style={s.remove}>Remove</Text></TouchableOpacity></View></View>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1},content:{padding:20},title:{fontSize:26,fontWeight:'800',marginBottom:8},note:{fontSize:12,color:'#666',marginBottom:16},sub:{fontWeight:'800',marginBottom:8},card:{borderWidth:1,borderColor:'#ddd',borderRadius:14,padding:16,marginBottom:14},input:{borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:12,marginBottom:10},button:{backgroundColor:'#111',padding:14,borderRadius:10},bt:{color:'#fff',textAlign:'center',fontWeight:'700'},oauth:{backgroundColor:'#111',padding:14,borderRadius:10},oauthText:{color:'#fff',textAlign:'center',fontWeight:'700'},error:{color:'#b00020',marginBottom:12},account:{borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:14,marginBottom:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},broker:{fontWeight:'800',fontSize:16},state:{marginTop:10},section:{fontWeight:'800',marginTop:6},action:{fontWeight:'700',paddingBottom:10},remove:{fontWeight:'700'}});